export const PHYSICS_TOPICS = [
  "Units And Dimensions, Basic Mathematics And Vectors",
  "Center Of Mass, Momentum And Collision",
  "Circular Motion",
  "Elasticity, Heat And Thermodynamics",
  "Fluid Mechanics",
  "Kinematics",
  "Newton's Laws Of Motion And Friction",
  "Rotational Dynamics",
  "Simple Harmonic Motion (SHM)",
  "Work, Energy And Power",
  "Alternating Currents (AC)",
  "Capacitance",
  "Current Electricity",
  "Electromagnetic Induction (EMI)",
  "Electromagnetic Waves And Wave Optics",
  "Electrostatics",
  "Errors In Measurements And Instruments",
  "Geometrical Optics",
  "Gravitation",
  "Magnetic Effects Of Current And Magnetism",
  "Modern Physics",
  "Principles Of Communication",
  "Semiconductors",
  "Sound Waves",
  "Waves On String",
] as const;

export const MATHS_TOPICS = [
  "Fundamentals Of Algebra",
  "Sequences And Series",
  "Binomial Theorem",
  "Circle",
  "Complex Numbers NCERT",
  "Ellipse",
  "Fundamentals Of Geometry",
  "Heights And Distances",
  "Hyperbola",
  "Limits And Derivatives NCERT",
  "Logarithm",
  "Mathematical Induction",
  "Mathematical Reasoning",
  "Parabola",
  "Permutation And Combination",
  "Probability NCERT",
  "Quadratic Equation",
  "Relations And Functions NCERT",
  "Sets, Relations And Functions",
  "Solution Of Triangle",
  "Statistics",
  "Straight Line",
  "Three Dimensional (3D) Geometry NCERT",
  "Trigonometric Equation",
  "Trigonometric Ratios And Identities",
  "Area Under The Curve",
  "Complex Numbers",
  "Continuity",
  "Definite Integration",
  "Determinants",
  "Differentiability",
  "Differential Equations",
  "Exponential And Logarithmic Series",
  "Function",
  "Indefinite Integration",
  "Inverse Trigonometric Functions",
  "Limits",
  "Linear Programming NCERT",
  "Matrices",
  "Maxima And Minima",
  "Methods Of Differentiation",
  "Probability",
  "Relations",
  "Tangent And Normal",
  "Three Dimensional Coordinate Geometry",
  "Vector",
] as const;

export const CHEMISTRY_TOPICS = [
  "Mole Concept",
  "Atomic Structure",
  "Acidic Strength And Basic Strength",
  "Chemical Bonding-I",
  "Chemical Bonding-II",
  "Chemical Equilibrium",
  "Classification of Organic Compounds, IUPAC Nomenclature and Isomerism",
  "Concentration Term",
  "Electron Displacement Effect",
  "Gaseous State (Ideal Gas)",
  "General Chemistry & Quantum Number",
  "Hydrocarbon",
  "Ionic Equilibrium",
  "Isomerism",
  "Periodic Table",
  "Purification and Characterisation of Organic Compounds",
  "Real Gas",
  "Redox",
  "The p-Block Elements (Group 13, 14)",
  "Thermochemistry",
  "Thermodynamics 1",
  "Thermodynamics 2",
  "Alcohol and Ethers",
  "Aromatic Compounds",
  "Biomolecules",
  "Carbonyl Compounds",
  "Carboxylic Acid and Its Derivatives, Aliphatic Amines",
  "Chemical Kinetics",
  "Chemistry in Everyday Life",
  "Coordination Compounds",
  "Electrochemistry",
  "Environmental Chemistry",
  "Haloalkane",
  "Hydrogen And Its Compounds",
  "Liquid Solution",
  "Metallurgy",
  "Oxidation",
  "Polymers, Practical Organic Chemistry and Separation Technique",
  "Reduction",
  "Salt Analysis",
  "Solid State",
  "Surface Chemistry",
  "The d-Block Elements",
  "The f-Block Elements",
  "The p-Block Elements (Group 15-18)",
  "The s-Block Elements",
] as const;

export function topicSlug(topic: string): string {
  return topic
    .toLowerCase()
    .replace(/['&,()]/g, "")
    .replace(/[/\s]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

export function slugToTopic(slug: string, topics: readonly string[]): string | undefined {
  return topics.find((t) => topicSlug(t) === slug);
}
