-- Run this in the Supabase SQL editor for the project connected to this app.
-- Full v2 schema for stepJEE

-- Main steps table
create table if not exists public.steps_data (
  id integer generated by default as identity primary key,
  problem text not null,
  title varchar(160) not null,
  steps jsonb not null check (jsonb_typeof(steps) = 'array'),
  image text,
  topic varchar(160),
  difficulty varchar(16),
  bookmarked boolean not null default false,
  hints jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists steps_data_created_at_idx on public.steps_data (created_at desc);
create index if not exists steps_data_topic_idx on public.steps_data (topic);
create index if not exists steps_data_bookmarked_idx on public.steps_data (bookmarked) where bookmarked = true;

-- Topic progress tracking
create table if not exists public.topic_progress (
  id integer generated by default as identity primary key,
  subject varchar(32) not null,
  topic varchar(160) not null,
  practiced_count integer not null default 0,
  confidence integer default 0,
  last_practiced_at timestamptz not null default now(),
  unique(subject, topic)
);

-- Reference formulas per topic
create table if not exists public.reference_formulas (
  id integer generated by default as identity primary key,
  subject varchar(32) not null,
  topic varchar(160) not null,
  formula_key varchar(160) not null,
  formula_latex text not null,
  "order" integer not null default 0
);

create index if not exists reference_formulas_topic_idx on public.reference_formulas (subject, topic);

-- Updated_at trigger
create or replace function public.set_steps_data_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_steps_data_updated_at on public.steps_data;
create trigger set_steps_data_updated_at
before update on public.steps_data
for each row
execute function public.set_steps_data_updated_at();

-- Row level security
alter table public.steps_data enable row level security;
alter table public.topic_progress enable row level security;
alter table public.reference_formulas enable row level security;

drop policy if exists "Public can read generated solutions" on public.steps_data;
create policy "Public can read generated solutions"
on public.steps_data
for select
using (true);

drop policy if exists "Public can create generated solutions" on public.steps_data;
create policy "Public can create generated solutions"
on public.steps_data
for insert
with check (true);

drop policy if exists "Public can update generated solutions" on public.steps_data;
create policy "Public can update generated solutions"
on public.steps_data
for update
using (true);

drop policy if exists "Public can delete generated solutions" on public.steps_data;
create policy "Public can delete generated solutions"
on public.steps_data
for delete
using (true);

-- Allow all on new tables
drop policy if exists "Public all topic_progress" on public.topic_progress;
create policy "Public all topic_progress"
on public.topic_progress
for all
using (true)
with check (true);

drop policy if exists "Public all reference_formulas" on public.reference_formulas;
create policy "Public all reference_formulas"
on public.reference_formulas
for all
using (true)
with check (true);
